# Mendefinisikan API Version dari object yg dibuat
apiVersion: v1

# Menentukan jenis object kubernetes yaitu Service
kind: Service

# Metadata digunakan untuk mendefinisikan informasi terkait Service
metadata:
  # Mendefinisikan nama service untuk backend
  name: karsajobs-service

# Mendefinisikan spesifikasi dari service
spec:
  # Tipe service untuk backend adalah nodeport
  type: NodePort

  # Menetapkan selector untuk mengelompokan resource pod yang dapat diakses oleh service ini
  selector:
    app: karsajobs
    tier: backend

  # Menetapkan port aplikasi
  ports:
    # mengeskpos port 8080 dan menetapkan nodeport dedicated 30000
    - port: 8080
      nodePort: 30000
